title: Nolan Clark
#logo: /assets/img/headshot_circle.png
description: - ğŸ“ M.S. Data Science - ğŸ“Š Visualizations - ğŸ¤– Machine Learning - ğŸ§  Large Language Models
#show_downloads: true
theme: jekyll-theme-minimal
